name: advanced_markdown_toolbar
description: A simple, flexible, and customizable toolbar to help editing Markdown content.
version: 0.1.0


environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1
